
gcc -std=c99 cl.c -lOpenCL -o cl
/opt/data/gcc-linaro-4.9-2016.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -std=c99 cl.c -o cl -L/opt/data/libmali/lib/ -lOpenCL -I/opt/data/libmali/include/original/ -ldrm
